name: build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2023.09.1
      options: --user root
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: build
      run: | 
        ./gradlew --no-daemon :app:assembleRelease  --stacktrace
        
    - name: Sign App Apk
      if: ${{ github.event_name == 'release'}}
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS_BASE_64 }}
        keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      env: 
        BUILD_TOOLS_VERSION: "33.0.1" 

    - name: List APK files in release directory
      run: ls -l app/build/outputs/apk/release/

    - name: Rename APK and Set Environment Variable
      run: |
        NEW_APK_NAME="TrelloWidget-${{ github.event.release.tag_name }}.apk"
        mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/$NEW_APK_NAME
        echo "NEW_APK_PATH=app/build/outputs/apk/release/$NEW_APK_NAME" >> $GITHUB_ENV

    - name: Upload Signed APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrelloWidget-${{ github.event.release.tag_name }}
        path: ${{ env.NEW_APK_PATH }}
    
    - name: Upload Signed APK to Release 
      uses: ncipollo/release-action@v1
      with:
        omitBody: true
        omitBodyDuringUpdate: true
        omitName: true
        allowUpdates: true
        updateOnlyUnreleased: false
        artifacts: ${{ env.NEW_APK_PATH }}
